name: Publish

on:
  push:
    branches:
      - main

jobs:
  pelican-publish:
    if: github.repository == 'PJECZ/consultas'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build web site
        run: |
          pelican content -o output -s publishconf.py
      - name: Update local branch
        run: |
          ghp-import output -b gh-pages
      - name: Push local site to remote
        run: |
          git push -f origin gh-pages
